# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5445:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
